name: Publish

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  packages: write
  contents: write
  attestations: write
  pull-requests: write

jobs:

  changelog:
    name: Create changelog
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Generate a changelog
        run: |
          if [ -f CHANGELOG.md ]; then
            echo hello >> CHANGELOG.md
          else
            echo first >> CHANGELOG.md
          fi
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit changelog
        run: |
          git checkout -b "changelog/v1.0.0"
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          set +e
          git add CHANGELOG.md
          git commit -m "chore: Update changelog"
          git push origin "changelog/v1.0.0" --force
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: "changelog/v1.0.0"
      - name: Create pull request for changelog
        run: |
            gh pr create --title "Changelog for 1.0.0" --body "This PR updates the changelog for version 1.0.0."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}